# Generated by Django 4.2.20 on 2025-06-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_populate_counties'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loandisbursement',
            options={},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='education_level',
            field=models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('diploma', 'Diploma'), ('degree', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], help_text='Select your highest level of education', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='next_of_kin',
            field=models.CharField(blank=True, help_text="Enter your next of kin's full name", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, help_text="Enter next of kin's phone number (e.g., 0712345678)", max_length=15, null=True),
        ),
    ]
