# Generated by Django 4.2.20 on 2025-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loandisbursement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Annual interest rate (%)', max_digits=5),
        ),
    ]
