# Generated by Django 4.2.20 on 2025-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loanapplication_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_purpose',
            field=models.CharField(blank=True, help_text='State the purpose of the loan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter your average monthly income', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=6.0, help_text='Annual interest rate (%)', max_digits=5),
        ),
    ]
