# Generated by Django 4.2.20 on 2025-07-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loanapplication_employment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_income',
            field=models.CharField(blank=True, help_text='Select your monthly income range', max_length=20, null=True),
        ),
    ]
